### ISSUE TITLE
Stream into stream

### ISSUE THREAD

**Issue by 1oglop1** [sandes/zipfly#80]
Hi, thank you for the inspirational code. 

I'm wondering if it's possible to adapt your code and make it compatible with S3 storage. 

I use `django-storages` and `boto3` client returns a streaming body (already open `fp`) and all metadata. 

I need a zipfile (or any other archive) to be created from the set of files during the `GET` request (not great but it has to be).

So to save the memory I have 2 options. 
1) Use `zipfly` as is and download files into a temporary location (and remove it after the operation)
2) Or better solution that doesn't require intermediate storage so I could pipe the content of `streaming body` into `zipfly` and return that as a streaming response. 

`streaming body` (many of them) -> `zipfly`(zip file) -> `streaming response`

Do you think that option two is possible? 
If so, could you please point out what pieces of code I should focus on to adapt zipfly?

Thank you

**Comment by sandes** [comment]
Hello :)
Mount your S3 bucket via FUSE using [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse) and stream the file using [django](https://github.com/BuzonIO/zipfly/blob/master/examples/streaming_django.py)
