### ISSUE TITLE
Is compression possible?

### ISSUE THREAD

**Issue by dezhin** [sandes/zipfly#92]
Hi,

I see that only uncompressed ZIP files are can be created with zipfly. What is the reason for that? I don't see any compression level specific code in ZipFly.generator, except file size estimation (which doesn't work for ZIP64 achives).

So, is compression just an unimplemented feature? Or are there any aspects which don't allow using compression for streaming made this way?

I understand that compression is often useless in streaming scenarios but it's not true in our case. We're looking for a replacement for ``zipstream-new`` which seems to be dead. ZipFly looks nice for us...

**Comment by pR0Ps** [comment]
@dezhin Another option you might want to look at would be [`zipstream-ng`](https://github.com/pR0Ps/zipstream-ng) (a library I maintain). Like this library and `zipstream-new` it creates zip files on the fly, but it also supports compression, zip64 extensions, and calculating the total size of the stream up front (with some restrictions).

**Comment by sandes** [comment]
@pR0Ps thanks for sharing zipstream-ng
