### ISSUE TITLE
Cannot include empty folders

### ISSUE THREAD

**Issue by rnixx** [sandes/zipfly#96]
Python's zipfile module supports writing empty folders to zip archive.

when trying with zipfly i get:

    File "/.../zipfly.py", line 211, in generator
        with open( path[self.filesystem], 'rb' ) as e:
    IsADirectoryError: [Errno 21] Is a directory: '/path/to/dir'

Is there an undocumented way for writing empty folders?

**Comment by sandes** [comment]
Hello,
It doesn't make any sense to include an option to add empty folders in zipfly.

You always can open a pr :)

**Comment by rnixx** [comment]
Well, there are valid usecases. This is no question about "sense".
